### ISSUE TITLE
Who are our audience and what kind of implication will our output have?

### ISSUE THREAD

**Issue by ElvisJiang24** [ElvisJiang24/DS4D-GroupProject#5]
We have to determine who are our targeted audience and how our video can influence them, general public is not a good description obviously.

**Comment by ShiyunYU** [comment]
I think readers is a good group in this discussion.

**Comment by ElvisJiang24** [comment]
Sounds good, crazy readers especially those who are interested in poems cuz we've got the largest amount of poems in our dataset. Shall we form a poem communication group for them? Just for implication of our video.

**Comment by YIHEEdinburgh** [comment]
In my opinion, it is hard to form a poem communication group while our video can be seem as a good advertisement that attracts more and more readers to use the modern library.

**Comment by ElvisJiang24** [comment]
Well, our audience is people who enjoy reading and wanna try new things thus they are willing to access the modernist library. As poems are involved a lot in it, its' reader may be interested in the library.
